version: '3'
services:
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./gh_project_list/:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  # Redis for Dramatiq broker
  redis:
    container_name: redis
    image: redis:3
    ports:
      - "6379:6379"

  # Postgres database
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres