# Generated by Django 3.2.9 on 2021-11-18 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhook',
            name='description',
        ),
    ]
